### ISSUE TITLE
Last version of RabbitMq client library not supported

### ISSUE THREAD

**Issue by jabacrack** [derekgreer/rabbitBus#10]
Nuget description say, that RabbitBus support RabbitMQ client version between 3.0.4 and 4, but in fact refuse work with 3.3.0

**Comment by derekgreer** [comment]
The NuGet declaration concerning which versions RabbitBus works with is theoretical based upon the rules of semantic versioning.  If RabbitBus works with version 3.0.4 but not with 3.3.0 then it means that RabbitMQ isn't properly following semantic versioning as they claim since an increment to the minor version number is supposed to mean that only new functionality has been introduced, not changes to existing functionality.

That said, can you describe the issue you are encountering (i.e. connection issues, missing messages, etc.?)

**Comment by jabacrack** [comment]
Bus.Publish throw next exception:

System.MissingMethodException was unhandled
  HResult=-2146233069
  Message=Method not found: 'Void RabbitMQ.Client.IModel.ExchangeDeclare(System.String, System.String, Boolean, Boolean, System.Collections.IDictionary)'.
  Source=RabbitBus
  StackTrace:
       at RabbitBus.MessagePublisher.PublishMessage(Object message, MessageProperties messageProperties, Action`2 replyAction)
       at RabbitBus.MessagePublisher.Publish(Object message, MessageProperties messageProperties)
       at RabbitBus.Bus.Publish[TMessage](TMessage message, MessageProperties messageProperties)
       at RabbitBus.BusExtensions.Publish[TMessage](IBus bus, TMessage message)
       at RiskSharp.Service.Test.RunScriptTestClient.RunScript(DocumentAddress documentAddress, String script) in F:\PROJECTS\Risk# Web\src\RiskSharp.Service.RabbitMQ.TestClient\RunScriptTestClient.cs:line 51
       at RiskSharp.Service.RabbitMQ.TestClient.Program.Main(String[] args) in F:\PROJECTS\Risk# Web\src\RiskSharp.Service.RabbitMQ.TestClient\Program.cs:line 29
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

P.S. 
And I apologize for the incomplete description of the error for the first time
